export default [
  { country: "USA", city: "Chicago", latitude: "41", longitude: "87" },
  { country: "China", city: "Lhasa", latitude: "29", longitude: "91" },
  { country: "Germany", city: "Hamburg", latitude: "53", longitude: "10" },
  { country: "Japan", city: "Niigata", latitude: "37", longitude: "139" },
  { country: "India", city: "New Delhi", latitude: "28", longitude: "77" },
  { country: "UK", city: "Edinburgh", latitude: "55", longitude: "03" },
  { country: "France", city: "Paris", latitude: "48", longitude: "2" },
  { country: "Brazil", city: "Recife", latitude: "8", longitude: "34" },
  { country: "Italy", city: "Milan", latitude: "45", longitude: "09" },
  { country: "Canada", city: "Yellowknife", latitude: "62", longitude: "114" },
  { country: "Russia", city: "Murmansk", latitude: "68", longitude: "33" },
  { country: "Mexico", city: "Guadalajara", latitude: "20", longitude: "103" },
  {
    country: "Australia",
    city: "Alice Springs",
    latitude: "23",
    longitude: "133",
  },
  { country: "SouthKorea", city: "Seoul", latitude: "37", longitude: "126" },
  { country: "Spain", city: "Bilbao", latitude: "43", longitude: "2" },
];
